// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remote_gpu.proto
// Protobuf C++ Version: 5.29.2

#include "remote_gpu.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace remoteGPU {

inline constexpr Output::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : out_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Output::Output(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct OutputDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OutputDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OutputDefaultTypeInternal() {}
  union {
    Output _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OutputDefaultTypeInternal _Output_default_instance_;

inline constexpr FileID::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FileID::FileID(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FileIDDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileIDDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileIDDefaultTypeInternal() {}
  union {
    FileID _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileIDDefaultTypeInternal _FileID_default_instance_;

inline constexpr File::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : code_{},
        commands_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR File::File(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FileDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileDefaultTypeInternal() {}
  union {
    File _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileDefaultTypeInternal _File_default_instance_;
}  // namespace remoteGPU
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_remote_5fgpu_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_remote_5fgpu_2eproto = nullptr;
const ::uint32_t
    TableStruct_remote_5fgpu_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::remoteGPU::File, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::remoteGPU::File, _impl_.code_),
        PROTOBUF_FIELD_OFFSET(::remoteGPU::File, _impl_.commands_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::remoteGPU::FileID, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::remoteGPU::FileID, _impl_.id_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::remoteGPU::Output, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::remoteGPU::Output, _impl_.out_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::remoteGPU::File)},
        {10, -1, -1, sizeof(::remoteGPU::FileID)},
        {19, -1, -1, sizeof(::remoteGPU::Output)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::remoteGPU::_File_default_instance_._instance,
    &::remoteGPU::_FileID_default_instance_._instance,
    &::remoteGPU::_Output_default_instance_._instance,
};
const char descriptor_table_protodef_remote_5fgpu_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020remote_gpu.proto\022\tremoteGPU\"&\n\004File\022\014\n"
    "\004code\030\001 \003(\t\022\020\n\010commands\030\002 \003(\t\"\024\n\006FileID\022"
    "\n\n\002id\030\001 \001(\005\"\025\n\006Output\022\013\n\003out\030\001 \003(\t2\250\001\n\tR"
    "emoteGPU\0222\n\nUploadFile\022\017.remoteGPU.File\032"
    "\021.remoteGPU.FileID\"\000\0224\n\014DownloadFile\022\021.r"
    "emoteGPU.FileID\032\017.remoteGPU.File\"\000\0221\n\007Ex"
    "ecute\022\021.remoteGPU.FileID\032\021.remoteGPU.Out"
    "put\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_remote_5fgpu_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_remote_5fgpu_2eproto = {
    false,
    false,
    293,
    descriptor_table_protodef_remote_5fgpu_2eproto,
    "remote_gpu.proto",
    &descriptor_table_remote_5fgpu_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_remote_5fgpu_2eproto::offsets,
    file_level_enum_descriptors_remote_5fgpu_2eproto,
    file_level_service_descriptors_remote_5fgpu_2eproto,
};
namespace remoteGPU {
// ===================================================================

class File::_Internal {
 public:
};

File::File(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:remoteGPU.File)
}
inline PROTOBUF_NDEBUG_INLINE File::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::remoteGPU::File& from_msg)
      : code_{visibility, arena, from.code_},
        commands_{visibility, arena, from.commands_},
        _cached_size_{0} {}

File::File(
    ::google::protobuf::Arena* arena,
    const File& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  File* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:remoteGPU.File)
}
inline PROTOBUF_NDEBUG_INLINE File::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : code_{visibility, arena},
        commands_{visibility, arena},
        _cached_size_{0} {}

inline void File::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
File::~File() {
  // @@protoc_insertion_point(destructor:remoteGPU.File)
  SharedDtor(*this);
}
inline void File::SharedDtor(MessageLite& self) {
  File& this_ = static_cast<File&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* File::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) File(arena);
}
constexpr auto File::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(File, _impl_.code_) +
          decltype(File::_impl_.code_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(File, _impl_.commands_) +
          decltype(File::_impl_.commands_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(File), alignof(File), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&File::PlacementNew_,
                                 sizeof(File),
                                 alignof(File));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull File::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_File_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &File::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<File>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &File::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<File>(), &File::ByteSizeLong,
            &File::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(File, _impl_._cached_size_),
        false,
    },
    &File::kDescriptorMethods,
    &descriptor_table_remote_5fgpu_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* File::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 35, 2> File::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::remoteGPU::File>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string commands = 2;
    {::_pbi::TcParser::FastUR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(File, _impl_.commands_)}},
    // repeated string code = 1;
    {::_pbi::TcParser::FastUR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(File, _impl_.code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string code = 1;
    {PROTOBUF_FIELD_OFFSET(File, _impl_.code_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // repeated string commands = 2;
    {PROTOBUF_FIELD_OFFSET(File, _impl_.commands_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\16\4\10\0\0\0\0\0"
    "remoteGPU.File"
    "code"
    "commands"
  }},
};

PROTOBUF_NOINLINE void File::Clear() {
// @@protoc_insertion_point(message_clear_start:remoteGPU.File)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.code_.Clear();
  _impl_.commands_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* File::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const File& this_ = static_cast<const File&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* File::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const File& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:remoteGPU.File)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated string code = 1;
          for (int i = 0, n = this_._internal_code_size(); i < n; ++i) {
            const auto& s = this_._internal_code().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "remoteGPU.File.code");
            target = stream->WriteString(1, s, target);
          }

          // repeated string commands = 2;
          for (int i = 0, n = this_._internal_commands_size(); i < n; ++i) {
            const auto& s = this_._internal_commands().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "remoteGPU.File.commands");
            target = stream->WriteString(2, s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:remoteGPU.File)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t File::ByteSizeLong(const MessageLite& base) {
          const File& this_ = static_cast<const File&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t File::ByteSizeLong() const {
          const File& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:remoteGPU.File)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated string code = 1;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_code().size());
              for (int i = 0, n = this_._internal_code().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_code().Get(i));
              }
            }
            // repeated string commands = 2;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_commands().size());
              for (int i = 0, n = this_._internal_commands().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_commands().Get(i));
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void File::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<File*>(&to_msg);
  auto& from = static_cast<const File&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:remoteGPU.File)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_code()->MergeFrom(from._internal_code());
  _this->_internal_mutable_commands()->MergeFrom(from._internal_commands());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void File::CopyFrom(const File& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:remoteGPU.File)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void File::InternalSwap(File* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.code_.InternalSwap(&other->_impl_.code_);
  _impl_.commands_.InternalSwap(&other->_impl_.commands_);
}

::google::protobuf::Metadata File::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class FileID::_Internal {
 public:
};

FileID::FileID(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:remoteGPU.FileID)
}
FileID::FileID(
    ::google::protobuf::Arena* arena, const FileID& from)
    : FileID(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE FileID::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void FileID::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
FileID::~FileID() {
  // @@protoc_insertion_point(destructor:remoteGPU.FileID)
  SharedDtor(*this);
}
inline void FileID::SharedDtor(MessageLite& self) {
  FileID& this_ = static_cast<FileID&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* FileID::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) FileID(arena);
}
constexpr auto FileID::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(FileID),
                                            alignof(FileID));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull FileID::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_FileID_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &FileID::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<FileID>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &FileID::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<FileID>(), &FileID::ByteSizeLong,
            &FileID::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(FileID, _impl_._cached_size_),
        false,
    },
    &FileID::kDescriptorMethods,
    &descriptor_table_remote_5fgpu_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* FileID::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> FileID::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::remoteGPU::FileID>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(FileID, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(FileID, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(FileID, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void FileID::Clear() {
// @@protoc_insertion_point(message_clear_start:remoteGPU.FileID)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* FileID::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const FileID& this_ = static_cast<const FileID&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* FileID::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const FileID& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:remoteGPU.FileID)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 id = 1;
          if (this_._internal_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_id(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:remoteGPU.FileID)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t FileID::ByteSizeLong(const MessageLite& base) {
          const FileID& this_ = static_cast<const FileID&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t FileID::ByteSizeLong() const {
          const FileID& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:remoteGPU.FileID)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 id = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void FileID::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<FileID*>(&to_msg);
  auto& from = static_cast<const FileID&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:remoteGPU.FileID)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileID::CopyFrom(const FileID& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:remoteGPU.FileID)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FileID::InternalSwap(FileID* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata FileID::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Output::_Internal {
 public:
};

Output::Output(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:remoteGPU.Output)
}
inline PROTOBUF_NDEBUG_INLINE Output::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::remoteGPU::Output& from_msg)
      : out_{visibility, arena, from.out_},
        _cached_size_{0} {}

Output::Output(
    ::google::protobuf::Arena* arena,
    const Output& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Output* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:remoteGPU.Output)
}
inline PROTOBUF_NDEBUG_INLINE Output::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : out_{visibility, arena},
        _cached_size_{0} {}

inline void Output::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Output::~Output() {
  // @@protoc_insertion_point(destructor:remoteGPU.Output)
  SharedDtor(*this);
}
inline void Output::SharedDtor(MessageLite& self) {
  Output& this_ = static_cast<Output&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* Output::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Output(arena);
}
constexpr auto Output::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Output, _impl_.out_) +
          decltype(Output::_impl_.out_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(Output), alignof(Output), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Output::PlacementNew_,
                                 sizeof(Output),
                                 alignof(Output));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Output::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Output_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Output::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Output>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Output::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Output>(), &Output::ByteSizeLong,
            &Output::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Output, _impl_._cached_size_),
        false,
    },
    &Output::kDescriptorMethods,
    &descriptor_table_remote_5fgpu_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Output::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 28, 2> Output::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::remoteGPU::Output>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string out = 1;
    {::_pbi::TcParser::FastUR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Output, _impl_.out_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string out = 1;
    {PROTOBUF_FIELD_OFFSET(Output, _impl_.out_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\20\3\0\0\0\0\0\0"
    "remoteGPU.Output"
    "out"
  }},
};

PROTOBUF_NOINLINE void Output::Clear() {
// @@protoc_insertion_point(message_clear_start:remoteGPU.Output)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.out_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Output::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Output& this_ = static_cast<const Output&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Output::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Output& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:remoteGPU.Output)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated string out = 1;
          for (int i = 0, n = this_._internal_out_size(); i < n; ++i) {
            const auto& s = this_._internal_out().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "remoteGPU.Output.out");
            target = stream->WriteString(1, s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:remoteGPU.Output)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Output::ByteSizeLong(const MessageLite& base) {
          const Output& this_ = static_cast<const Output&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Output::ByteSizeLong() const {
          const Output& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:remoteGPU.Output)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated string out = 1;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_out().size());
              for (int i = 0, n = this_._internal_out().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_out().Get(i));
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Output::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Output*>(&to_msg);
  auto& from = static_cast<const Output&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:remoteGPU.Output)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_out()->MergeFrom(from._internal_out());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Output::CopyFrom(const Output& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:remoteGPU.Output)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Output::InternalSwap(Output* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.out_.InternalSwap(&other->_impl_.out_);
}

::google::protobuf::Metadata Output::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace remoteGPU
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_remote_5fgpu_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
