// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: fileshare.proto

#include "fileshare.pb.h"
#include "fileshare.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace gpu_buddy {

static const char* FileShare_method_names[] = {
  "/gpu_buddy.FileShare/Execute",
};

std::unique_ptr< FileShare::Stub> FileShare::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FileShare::Stub> stub(new FileShare::Stub(channel, options));
  return stub;
}

FileShare::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Execute_(FileShare_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::gpu_buddy::InputFile, ::gpu_buddy::Output>* FileShare::Stub::ExecuteRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::gpu_buddy::InputFile, ::gpu_buddy::Output>::Create(channel_.get(), rpcmethod_Execute_, context);
}

void FileShare::Stub::async::Execute(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::gpu_buddy::InputFile,::gpu_buddy::Output>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::gpu_buddy::InputFile,::gpu_buddy::Output>::Create(stub_->channel_.get(), stub_->rpcmethod_Execute_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::gpu_buddy::InputFile, ::gpu_buddy::Output>* FileShare::Stub::AsyncExecuteRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::gpu_buddy::InputFile, ::gpu_buddy::Output>::Create(channel_.get(), cq, rpcmethod_Execute_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::gpu_buddy::InputFile, ::gpu_buddy::Output>* FileShare::Stub::PrepareAsyncExecuteRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::gpu_buddy::InputFile, ::gpu_buddy::Output>::Create(channel_.get(), cq, rpcmethod_Execute_, context, false, nullptr);
}

FileShare::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileShare_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< FileShare::Service, ::gpu_buddy::InputFile, ::gpu_buddy::Output>(
          [](FileShare::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::gpu_buddy::Output,
             ::gpu_buddy::InputFile>* stream) {
               return service->Execute(ctx, stream);
             }, this)));
}

FileShare::Service::~Service() {
}

::grpc::Status FileShare::Service::Execute(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::gpu_buddy::Output, ::gpu_buddy::InputFile>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace gpu_buddy

