// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: gpu.proto

#include "gpu.pb.h"
#include "gpu.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace example {

static const char* RemoteGPU_method_names[] = {
  "/example.RemoteGPU/SendStrings",
};

std::unique_ptr< RemoteGPU::Stub> RemoteGPU::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RemoteGPU::Stub> stub(new RemoteGPU::Stub(channel, options));
  return stub;
}

RemoteGPU::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendStrings_(RemoteGPU_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RemoteGPU::Stub::SendStrings(::grpc::ClientContext* context, const ::example::File& request, ::example::StringResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::example::File, ::example::StringResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendStrings_, context, request, response);
}

void RemoteGPU::Stub::async::SendStrings(::grpc::ClientContext* context, const ::example::File* request, ::example::StringResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::example::File, ::example::StringResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendStrings_, context, request, response, std::move(f));
}

void RemoteGPU::Stub::async::SendStrings(::grpc::ClientContext* context, const ::example::File* request, ::example::StringResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendStrings_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::example::StringResponse>* RemoteGPU::Stub::PrepareAsyncSendStringsRaw(::grpc::ClientContext* context, const ::example::File& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::example::StringResponse, ::example::File, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendStrings_, context, request);
}

::grpc::ClientAsyncResponseReader< ::example::StringResponse>* RemoteGPU::Stub::AsyncSendStringsRaw(::grpc::ClientContext* context, const ::example::File& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendStringsRaw(context, request, cq);
  result->StartCall();
  return result;
}

RemoteGPU::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RemoteGPU_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RemoteGPU::Service, ::example::File, ::example::StringResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RemoteGPU::Service* service,
             ::grpc::ServerContext* ctx,
             const ::example::File* req,
             ::example::StringResponse* resp) {
               return service->SendStrings(ctx, req, resp);
             }, this)));
}

RemoteGPU::Service::~Service() {
}

::grpc::Status RemoteGPU::Service::SendStrings(::grpc::ServerContext* context, const ::example::File* request, ::example::StringResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace example

