// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: gpu.proto
#ifndef GRPC_gpu_2eproto__INCLUDED
#define GRPC_gpu_2eproto__INCLUDED

#include "gpu.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace example {

class RemoteGPU final {
 public:
  static constexpr char const* service_full_name() {
    return "example.RemoteGPU";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SendStrings(::grpc::ClientContext* context, const ::example::File& request, ::example::StringResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::example::StringResponse>> AsyncSendStrings(::grpc::ClientContext* context, const ::example::File& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::example::StringResponse>>(AsyncSendStringsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::example::StringResponse>> PrepareAsyncSendStrings(::grpc::ClientContext* context, const ::example::File& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::example::StringResponse>>(PrepareAsyncSendStringsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SendStrings(::grpc::ClientContext* context, const ::example::File* request, ::example::StringResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendStrings(::grpc::ClientContext* context, const ::example::File* request, ::example::StringResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::example::StringResponse>* AsyncSendStringsRaw(::grpc::ClientContext* context, const ::example::File& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::example::StringResponse>* PrepareAsyncSendStringsRaw(::grpc::ClientContext* context, const ::example::File& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendStrings(::grpc::ClientContext* context, const ::example::File& request, ::example::StringResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::example::StringResponse>> AsyncSendStrings(::grpc::ClientContext* context, const ::example::File& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::example::StringResponse>>(AsyncSendStringsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::example::StringResponse>> PrepareAsyncSendStrings(::grpc::ClientContext* context, const ::example::File& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::example::StringResponse>>(PrepareAsyncSendStringsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendStrings(::grpc::ClientContext* context, const ::example::File* request, ::example::StringResponse* response, std::function<void(::grpc::Status)>) override;
      void SendStrings(::grpc::ClientContext* context, const ::example::File* request, ::example::StringResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::example::StringResponse>* AsyncSendStringsRaw(::grpc::ClientContext* context, const ::example::File& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::example::StringResponse>* PrepareAsyncSendStringsRaw(::grpc::ClientContext* context, const ::example::File& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendStrings_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendStrings(::grpc::ServerContext* context, const ::example::File* request, ::example::StringResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendStrings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendStrings() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendStrings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendStrings(::grpc::ServerContext* /*context*/, const ::example::File* /*request*/, ::example::StringResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendStrings(::grpc::ServerContext* context, ::example::File* request, ::grpc::ServerAsyncResponseWriter< ::example::StringResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendStrings<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendStrings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendStrings() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::example::File, ::example::StringResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::example::File* request, ::example::StringResponse* response) { return this->SendStrings(context, request, response); }));}
    void SetMessageAllocatorFor_SendStrings(
        ::grpc::MessageAllocator< ::example::File, ::example::StringResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::example::File, ::example::StringResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendStrings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendStrings(::grpc::ServerContext* /*context*/, const ::example::File* /*request*/, ::example::StringResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendStrings(
      ::grpc::CallbackServerContext* /*context*/, const ::example::File* /*request*/, ::example::StringResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendStrings<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendStrings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendStrings() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendStrings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendStrings(::grpc::ServerContext* /*context*/, const ::example::File* /*request*/, ::example::StringResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendStrings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendStrings() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendStrings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendStrings(::grpc::ServerContext* /*context*/, const ::example::File* /*request*/, ::example::StringResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendStrings(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendStrings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendStrings() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendStrings(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendStrings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendStrings(::grpc::ServerContext* /*context*/, const ::example::File* /*request*/, ::example::StringResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendStrings(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendStrings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendStrings() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::example::File, ::example::StringResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::example::File, ::example::StringResponse>* streamer) {
                       return this->StreamedSendStrings(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendStrings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendStrings(::grpc::ServerContext* /*context*/, const ::example::File* /*request*/, ::example::StringResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendStrings(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::example::File,::example::StringResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendStrings<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendStrings<Service > StreamedService;
};

}  // namespace example


#endif  // GRPC_gpu_2eproto__INCLUDED
